# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Add any project specific keep options here:


# ============================================================
# Size optimization rules (auto-generated by expo-plugin-architectures)
# ============================================================

# React Native / JNI bridge — must be kept for JS<->native calls
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class com.facebook.soloader.** { *; }

# Expo modules
-keep class expo.modules.** { *; }

# Reanimated & Gesture Handler
-keep class com.swmansion.reanimated.** { *; }
-keep class com.swmansion.gesturehandler.** { *; }
-keep class com.swmansion.rnscreens.** { *; }

# Notifee
-keep class io.invertase.notifee.** { *; }
-keep class app.notifee.core.** { *; }

# MMKV
-keep class com.tencent.mmkv.** { *; }

# FFmpeg Kit
-keep class com.arthenica.ffmpegkit.** { *; }

# Vision Camera
-keep class com.mrousavy.camera.** { *; }

# Annotations & debug info
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keepattributes Signature
-keepattributes Exceptions

# Keep exception subclasses (crash reporting)
-keep public class * extends java.lang.Exception

# OkHttp / networking
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }

# Kotlin
-keep class kotlin.** { *; }
-keep class kotlin.Metadata { *; }
-dontwarn kotlin.**
-keepclassmembers class **$WhenMappings { <fields>; }
-keepclassmembers class kotlin.Metadata { public <methods>; }
-keepclassmembernames class kotlinx.** { volatile <fields>; }

# Native methods
-keepclasseswithmembernames class * {
    native <methods>;
}

# Enums
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# JavaScript interface (WebView bridge)
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
